### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by Indemnity83** [M165437/laravel-blueprint-docs#10]
The version constraints currently limit using this package in 5.4 or 5.5; would be good to add 5.6.

**Comment by M165437** [comment]
Some dependencies need to update as well. I'm working on it. Expect support soonish.

**Comment by M165437** [comment]
I submitted a [pull request to drafter-php](https://github.com/hendrikmaus/drafter-php/pull/6), the dependency that needs to be updated. As soon as it is accepted, I'll update this package.

**Comment by M165437** [comment]
Version 0.4.0 of this package now supports Laravel 5.6. I didn't want to wait longer and temporarily require my fork of drafter-php until the original author merges my pull request or updates his package himself. Thanks for your patience.
