### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by alexgiuvara** [M165437/laravel-blueprint-docs#13]
```json
"message": "Undefined offset: 0",
"exception": "ErrorException",
"file": "/app/vendor/m165437/laravel-blueprint-docs/src/Elements/Action.php",
"line": 71,

**Comment by M165437** [comment]
Can you give some context? What does your *.apib look like?

**Comment by M165437** [comment]
Just saw your PR. Thanks! Will have a closer look tomorrow.

**Comment by alexgiuvara** [comment]
We moved to Swagger 3. I have found an easy and fun way to deal with the swagger file.
I will write an article about that.

Best wishes

**Comment by Allross92** [comment]
The same issue on Lumen 5.8 #53 {main} {"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /.../vendor/m165437/laravel-blueprint-docs/src/Elements/Action.php:67)

**Comment by M165437** [comment]
Lumen is not supported
