### ISSUE TITLE
Error when loading /api-documentation

### ISSUE THREAD

**Issue by eschopler1** [M165437/laravel-blueprint-docs#16]
Type error: Argument 1 passed to M165437\BlueprintDocs\Elements\Api::__construct() must be an instance of Hmaus\Reynaldo\Elements\ApiDescriptionRoot, null given, called in /home/vagrant/Code/Laravel/cDVR/vendor/m165437/laravel-blueprint-docs/src/BlueprintDocs.php on line 88

I followed the instructions and am receiving this error. Could this be related to the https://github.com/M165437/laravel-blueprint-docs/issues/12 ?

**Comment by M165437** [comment]
What is the name and location of your blueprint file? By default Blueprint Docs looks for a file named `blueprint.apib` in the root directory of your Laravel project.

**Comment by jhoff** [comment]
FWIW, I got this error trying to use the 4.x branch of [drafter](https://github.com/apiaryio/drafter). It seems that the reynaldo package only supports 3.2.7 of drafter.

**Comment by Grummfy** [comment]
see https://github.com/hendrikmaus/reynaldo/pull/4
