### ISSUE TITLE
vendor/bin/drafter not found

### ISSUE THREAD

**Issue by s2925534** [M165437/laravel-blueprint-docs#17]
I understand you are using a external lib such as drafter-php but regardless of what you build the dependencies should be installed via your composer.lock and not leaving us with a issue such as vendor/bin/drafter not existing due to the drafter installation not creating this. I cannot use this as no drafter installation right now is giving me this file under the bin folder.
Look at this exception:

Exception {#1416 ▼
  #message: "sh: 1: /var/www/portal/vendor/bin/drafter: not found\n"
  #code: 0
  #file: "/var/www/portal/vendor/hmaus/drafter-php/src/Drafter.php"
  #line: 165
  trace: {▼
    /var/www/portal/vendor/hmaus/drafter-php/src/Drafter.php:165 {▶}
    /var/www/portal/vendor/m165437/laravel-blueprint-docs/src/BlueprintDocs.php:59 {▶}
    /var/www/portal/app/Http/Controllers/ApiDocumentationController.php:28 {▼
      ›             $api = $blueprintDocs
      ›                 ->parse(config('blueprintdocs.blueprint_file'))
      › //            ->parse(config('blueprintdocs.blueprint_file'))
      arguments: {▶}
    }
    ...

**Comment by M165437** [comment]
As the README clearly states: **Drafter is not included** and must be installed beforehand. Use the [Drafter Installer](https://github.com/hendrikmaus/drafter-installer) composer package to install Drafter.

**Comment by cacpmw** [comment]
@M165437 I do have drafter under vendor/bin/ and still get this same error. any suggestion?

**Comment by M165437** [comment]
Which version of Drafter did you install? Use 3.2.7 for now (4 isn’t supported yet).

**Comment by cacpmw** [comment]
@M165437 I included this in the require:
`"hmaus/drafter-installer": "^1.0",`

and this in the extra:
`        "drafter-installer-tag": "v3.2.7",
`

I also added the post install and update and the install draft scripts.

**Comment by M165437** [comment]
Does the command `vendor/bin/drafter --help` work?

**Comment by zachisit** [comment]
`-bash: vendor/bin/drafter: No such file or directory` when ran on local and also in my vagrant box.

**Comment by sven-ahrens** [comment]
I've just installed it and it doesnt work either. Same problem.

drafter binary file exists in ``/application/vendor/bin/drafter``

> sh: 1: /application/vendor/bin/drafter: not found

composer.json:

```
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "install-drafter": "Hmaus\\Drafter\\Installer::installDrafter",
        "post-install-cmd": [
            "@install-drafter"
        ],
        "post-update-cmd": [
            "@install-drafter"
        ]
    }
    "extra": {
        "laravel": {
            "dont-discover": []
        },
        "drafter-installer-tag": "v3.2.7"
    },
```

**Comment by sven-ahrens** [comment]
It seems like this drafter binary is broken because I cannot run it. Other binary files like carbon (Laravel) or others can be executed
