### ISSUE TITLE
'M165437\BlueprintDoc\BlueprintDocServiceProvider' not found

### ISSUE THREAD

**Issue by iampawan31** [M165437/laravel-blueprint-docs#2]
I am trying to make this package work in Laravel 5.5. But i am getting the following error

`'M165437\BlueprintDoc\BlueprintDocServiceProvider' not found`

**Comment by M165437** [comment]
Did you update to 5.5 from 5.4? Check if your composer.json file includes:

```
"scripts": {
    ....
    "post-autoload-dump": [
        ...
        "@php artisan package:discover"
    ],
}
```

Compare it to the [package.json of a fresh install of Laravel 5.5](https://github.com/laravel/laravel/blob/master/composer.json).

You can also run `php artisan package:discover` manually.

**Comment by M165437** [comment]
You were right, the problem was a typo in the installation instructions. The service provider path was wrong. Please correct it in your `config/app.php` and it will work.

```
// config/app.php
'providers' => [
    ...
    M165437\BlueprintDocs\BlueprintDocsServiceProvider::class,
];
```
