### ISSUE TITLE
How to document QueryBuilder parameters?

### ISSUE THREAD

**Issue by anychmguy** [M165437/laravel-blueprint-docs#20]
Hi
I'm usin https://github.com/spatie/laravel-query-builder in my API, which requires parameters like:

https://example.org/api/cars?filter[model_id]=1&filter[brand_id]=2

But when trying to write API Blueprint for this, this package does not render well those parameters.

I tried the following variations:
![screenshot_20180817_073059](https://user-images.githubusercontent.com/42460276/44249316-92fb5280-a1ef-11e8-8407-426ba6977d8c.png)

But it does not print nothing in the parameters section

Also tried encoding the characters
![screenshot_20180817_073223](https://user-images.githubusercontent.com/42460276/44249347-b8885c00-a1ef-11e8-8e57-19e08c7230fe.png)

But it prints the  codes instead of the characters:
![screenshot_20180817_072614](https://user-images.githubusercontent.com/42460276/44249138-de613100-a1ee-11e8-8b31-4fd86dbda7c7.png)

Also tried escaping the parameters:
![screenshot_20180817_072921](https://user-images.githubusercontent.com/42460276/44249250-562f5b80-a1ef-11e8-8877-4172bee72422.png)

but it does not print the parameters section

**Comment by M165437** [comment]
I will have a look

**Comment by M165437** [comment]
@anychmguy API Blueprint doesn't support associative arrays as url parameteres. Have a look at the discussion of [api-blueprint/issues/240](https://github.com/apiaryio/api-blueprint/issues/240). There is an [MSON RFC proposal](https://github.com/apiaryio/api-blueprint-rfcs/pull/3) addressing this issue, but it hasn't been implemented yet.

In the meantime, plain parameters are an easy way to add basic filtering:

```markdown
## Cars [/cars{?model}{&brand}]

Cars API

### Gets a list of cars [GET]

Get the list of registered cars

+ Request
    + Headers

        Authorization: Bearer <token>

+ Parameters
    + model: `123` (number) - Model of the Car
    + brand: `456` (number) - Brand of the Car
```
