### ISSUE TITLE
Parsing Error Rendering Documentation

### ISSUE THREAD

**Issue by bricehartmann** [M165437/laravel-blueprint-docs#21]
I am receiving the following error when attempting to render the [boilerplate API Blueprint file](https://github.com/jsynowiec/api-blueprint-boilerplate/blob/master/src/api.apib) mentioned in the docs. This file is saved as `test.apib` at the root of my project.

```
Argument 1 passed to M165437\BlueprintDocs\Elements\Api::__construct() must be an instance of Hmaus\Reynaldo\Elements\ApiDescriptionRoot, null given, called in /var/www/vendor/m165437/laravel-blueprint-docs/src/BlueprintDocs.php on line 88
```

My Laravel version is 5.8 and my Drafter version is v4.0.0-pre.5

Below is my configuration:
```
<?php

return [
    'route' => 'docs',
    'condense_navigation' => false,
    'blueprint_file' => base_path('test.apib'),
    'drafter' => base_path('vendor/bin/drafter')
];
```

The issue seems to be that this `parseRefract` method is returning `null` https://github.com/M165437/laravel-blueprint-docs/blob/master/src/BlueprintDocs.php#L74
because this `getFirstElementByType` method is returning null https://github.com/hendrikmaus/reynaldo/blob/master/src/Elements/ParseResultElement.php#L9.
Digging deeper, this seems to be caused by this conditional never being true (https://github.com/hendrikmaus/reynaldo/blob/master/src/Parser/RefractParser.php#L147) because this method call (https://github.com/hendrikmaus/reynaldo/blob/master/src/Parser/RefractParser.php#L166) is failing to detect the "Master Category" of the document.

If I add a `dd($className, $element);` above this line (https://github.com/hendrikmaus/reynaldo/blob/master/src/Parser/RefractParser.php#L180), the output is attached.
[dd_output.txt](https://github.com/M165437/laravel-blueprint-docs/files/3170626/dd_output.txt)

As you can see from the attached output and the `hasClass` method, the "api" class is not being found because the method expects the content of `$element['meta']['classes']` to be a string, but it's actually an array.

Can someone please help me debug this?

**Comment by bricehartmann** [comment]
I was using a pre-release of drafter, hence the breaking changes. I downgraded to Drafter v3.2.7 which resolved the issue 👍

**Comment by Grummfy** [comment]
see https://github.com/hendrikmaus/reynaldo/pull/4

**Comment by rico** [comment]
Same problem with drafter 4.1.0. After reinstalling drafter 3.2.7 (`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/9661bdaae9337f0165398207cf49b3467006bdc2/Formula/drafter.rb`
) everything worked fine.
