### ISSUE TITLE
Multiple blueprint files

### ISSUE THREAD

**Issue by KieronWiltshire** [M165437/laravel-blueprint-docs#22]
The APIBlueprint specification doesn't consider split files, and maybe rightly so, but anyways, I'd really like the ability for you to expose multiple files via multiple routes, maybe something like:

```
return [

    /*
    |--------------------------------------------------------------------------
    | Blueprint Docs
    |--------------------------------------------------------------------------
    |
    | Find your rendered docs at the given route or set route to false if you
    | want to use your own route and controller. Provide a fully qualified
    | path to your API blueprint as well as to the required Drafter CLI.
    |
    */

    'condense_navigation' => false,

    'blueprints' => [
        'api-documentation' => base_path('blueprint.apib'),
    ],

    'drafter' => base_path('vendor/bin/drafter')

];
```

Also maybe expose an blade directive to allow something like

```
@apiblueprint('blueprint.apib')
```

**Comment by M165437** [comment]
Hi @KieronWiltshire, I don't plan to support multiple files via config file. You can, however, use your own routes and controllers to render multiple docs. Have a look at `vendor/m165437/laravel-blueprint-docs/src/BlueprintDocsController.php` to get an idea on how to set it up. Cheers!
