### ISSUE TITLE
Request specifications are not parsed and shown in HTML.

### ISSUE THREAD

**Issue by nielsiano** [M165437/laravel-blueprint-docs#3]
Requests are not visible.

Using this simple example:
https://raw.githubusercontent.com/apiaryio/api-blueprint/2b1e66667152fc0f5a2a2a5c2d99d27bd24af8ba/examples/13.%20Named%20Endpoints.md

Ends up missing the request definitions and only shows `Headers`:

![image](https://user-images.githubusercontent.com/947684/30906370-f7592cba-a377-11e7-876b-85a66dc3caf8.png)

**Comment by M165437** [comment]
Thanks for finding this! I fixed it in the latest release [0.1.2](https://github.com/M165437/laravel-blueprint-docs/tree/v0.1.2).

**Comment by nielsiano** [comment]
Awesome. Thanks, @M165437
