### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by vytsci** [M165437/laravel-blueprint-docs#42]
I can compile this easily on host machine, but for docker and centos server side i was just unable to solve this issue. Maybe there should be some pre compiled binaries included. On all other environments I only can get up to GLIBCXX_3.4.25. I know this is not an issue with this package, but rather its dependencies, but this package has way more activity.

**Comment by M165437** [comment]
Sorry to hear but I can't help if it's an issue with a dependency. Have you tried raising the issue there?
