### ISSUE TITLE
rendering parameter type

### ISSUE THREAD

**Issue by chilio** [M165437/laravel-blueprint-docs#5]
I have a problem, where defined parameter type is always rendered as string. 
No matter what is entered in source for example:
`+ Parameters
    + id: (integer, required) - id`
I have tried also other types, for example: int, date, time, etc
Is it a bug or am I missing something?

BTW. I am using this with api:docs generator from dingo api.

**Comment by M165437** [comment]
Please post a whole example blueprint, something that renders (even if it doesn't render as expected). Cheers!

**Comment by chilio** [comment]
I'm not using dingo anymore and therefore hard to reproduce this issue...
