### ISSUE TITLE
Feature Request: Multiple Request/Response Pairs

### ISSUE THREAD

**Issue by spawnia** [M165437/laravel-blueprint-docs#9]
Hi, loving the Package so far!

I was just wondering if you have thought about supporting pairs of parameterized requests and response.
API Blueprint allows specifying different responses based on which parameters are added in the request, so it would be nice to show that in the Documentation.

Let me know if you have plans to implement something like that and if not, maybe i can take a shot at it and make a pull request.

Thanks

**Comment by M165437** [comment]
Hi Benedikt,

thank you! Your feedback means a lot to me. In fact, it's the first direct feedback I've got after more than 1200 downloads. :)

Could you post an example blueprint? What does it look like? If you'd like to contribute this feature, go for it!
